// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArg8_C3nVanW37ria6RuThQp45evyisBc',
    appId: '1:720425832901:web:a56c37e67630b00f5ffbac',
    messagingSenderId: '720425832901',
    projectId: 'fir-flutter-codelab-eac53',
    authDomain: 'fir-flutter-codelab-eac53.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-eac53.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTntfIkb9tulEycF9Lu1cO7edtHQHP25o',
    appId: '1:720425832901:android:9801359529b45b545ffbac',
    messagingSenderId: '720425832901',
    projectId: 'fir-flutter-codelab-eac53',
    storageBucket: 'fir-flutter-codelab-eac53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsIvFMDsq7oxhTVMpJUXgABUfYffEJcXY',
    appId: '1:720425832901:ios:a90533d551cc55935ffbac',
    messagingSenderId: '720425832901',
    projectId: 'fir-flutter-codelab-eac53',
    storageBucket: 'fir-flutter-codelab-eac53.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsIvFMDsq7oxhTVMpJUXgABUfYffEJcXY',
    appId: '1:720425832901:ios:a90533d551cc55935ffbac',
    messagingSenderId: '720425832901',
    projectId: 'fir-flutter-codelab-eac53',
    storageBucket: 'fir-flutter-codelab-eac53.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

}